# Generated by Django 4.2.30 on 2026-05-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('paciente', models.CharField(max_length=100)),
                ('fecha_cita', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'citas',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
    ]
